# Generated by Django 5.1.4 on 2024-12-07 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masked_pan', models.CharField(max_length=18)),
                ('encrypted_pan', models.TextField()),
                ('encrypted_expiry', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionArchive',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masked_pan', models.CharField(max_length=18)),
                ('encrypted_pan', models.TextField()),
                ('encrypted_expiry', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
