# Generated by Django 5.1.3 on 2024-11-09 12:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('reated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masked_pan', models.CharField(max_length=18)),
                ('encrypted_pan', models.CharField()),
                ('encrypted_expiry', models.CharField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
