# Generated by Django 5.1.3 on 2024-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
