# Generated by Django 5.1.3 on 2024-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_reated_at_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='encrypted_expiry',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='encrypted_pan',
            field=models.TextField(),
        ),
    ]
