# Generated by Django 5.1.4 on 2025-01-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "Nigerian Naira"), ("USD", "US Dollar")],
                default="NGN",
                max_length=3,
            ),
        ),
    ]
