# Generated by Django 5.1.4 on 2025-01-18 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_wallet_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="wallet_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
