# Generated by Django 5.1.4 on 2025-01-18 01:08

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Wallet = apps.get_model("wallets", "Wallet")
    for wallet in Wallet.objects.all():
        wallet.wallet_id = uuid.uuid4()
        wallet.save()

class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_wallet_wallet_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
