# Generated by Django 5.1.4 on 2025-01-18 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_auto_20250118_0108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
