# Generated by Django 5.1.4 on 2025-01-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_auto_20250118_0108"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
