# Generated by Django 5.1.4 on 2025-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0006_transaction_payment_provider_transaction_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10
            ),
        ),
    ]
