# Generated by Django 5.1.4 on 2025-01-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0008_alter_wallet_user_alter_wallet_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="credit_source_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="credit_source_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="debit_destination_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="debit_destination_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
