# Generated by Django 5.1.4 on 2025-01-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("mustardauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kyc_level",
            field=models.CharField(
                choices=[
                    ("verified_email", "Verified Email"),
                    ("verified_bvn", "Verified BVN"),
                    ("verified_nin", "Verified NIN"),
                ],
                default="verified_email",
                help_text="The KYC level the user has completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tier",
            field=models.CharField(
                choices=[
                    ("tier_1", "Tier 1"),
                    ("tier_2", "Tier 2"),
                    ("tier_3", "Tier 3"),
                ],
                default="tier_1",
                help_text="The current transaction tier of the user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_set",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_permissions_set",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
